---
title: "Social Network Study: Network Survey Data Cleaning"
author: "Andrea Courtney, Natalie Samuels, & Matt Leipzig"
date: "12/10/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,root.dir="../scripts")
#setwd("~/Documents/POSTDOC/StanfordNetworkStudy/Data/raw_de-identified_data/de-ID_Network_Fall2018_Week9/")
library(plyr)
library(tidyverse)
```

## Load data

Merge all dorm files

Data files have been anonymized and assigned a random participant ID (PID), dorm ID (DID), and network ID (NID). 
```{r tidyverse, echo=FALSE}
filenames <- list.files()
data <- ldply(filenames, read.csv, header=TRUE) 

# Recode values
data <- data %>% mutate_at(c("PoliticalAttitudes1","PoliticalAttitudes2","PoliticalAttitudes3","PoliticalAttitudes4","PoliticalAttitudes5","PoliticalAttitudes6","GroupPolitics1","GroupPolitics2","GroupPolitics3","GroupPolitics4","GroupPolitics5","GroupPolitics6","MoralConvictions1","MoralConvictions2","MoralConvictions3","MoralConvictions4"), funs(recode(., "18" = 0, "19" = 1, "20" = 2, "21" = 3, "22" = 4, "23" = 5, "24" = 6)))

# Filter out 17 year olds and bad subjects (self nominations already removed)
data$Age <- as.numeric(data$Age)
data <- filter(data, Age >= 18)
data <- filter(data, PID != "cGhC03VDka")
data <- data %>% mutate(entry = row_number())

# filter out people with less than 80% progress & duplicates


# Label dorms
data$dorm <- recode(data$NID, "13"="Norcliffe", "1"="Alondra", "2"="Cedro", "3"="EAST", "4"="FroSoCo", "15"="WestFloMo", "5"="JRo", "6"="Kimball", "7"="Larkin", "11"="Meier", "8"="Okada", "9"="Twain", "10"="Ujamaa")

```

## Convert to long format and summarize data
Create a separate data frame for each network type
```{r, echo=FALSE}
library(naniar)

# Close friends
CloseFrds <- select(data,c(PID,entry,Age,DID,NID,dorm,CloseFrds_1:CloseFrds_6))
CloseFrds <- gather(CloseFrds, key = "CloseFrds", value = "Target", CloseFrds_1:CloseFrds_6)
CloseFrds <- replace_with_na(CloseFrds, replace = list(Target = c("NONE","None")))
CloseFrds <- CloseFrds %>% group_by(PID,entry,Target) %>% add_count(Target)

# Spend time
SpendTime <- select(data,c(PID,entry,Age,DID,NID,dorm,SpendTime_1:SpendTime_6))
SpendTime <- gather(SpendTime, key = "SpendTime", value = "Target", SpendTime_1:SpendTime_6)
SpendTime <- replace_with_na(SpendTime, replace = list(Target = c("NONE","None")))
SpendTime <- SpendTime %>% group_by(PID,entry,Target) %>% add_count(Target)

# Social Advice
SocAdvice <- select(data,c(PID,entry,Age,DID,NID,dorm,SocAdvice_1:SocAdvice_6))
SocAdvice <- gather(SocAdvice, key = "SocAdvice", value = "Target", SocAdvice_1:SocAdvice_6)
SocAdvice <- replace_with_na(SocAdvice, replace = list(Target = c("NONE","None")))
SocAdvice <- SocAdvice %>% group_by(PID,entry,Target) %>% add_count(Target)

# Negative Emotional Support
NegEmoSupp <- select(data,c(PID,entry,Age,DID,NID,dorm,NegEmoSupp_1:NegEmoSupp_6))
NegEmoSupp <- gather(NegEmoSupp, key = "NegEmoSupp", value = "Target", NegEmoSupp_1:NegEmoSupp_6)
NegEmoSupp <- replace_with_na(NegEmoSupp, replace = list(Target = c("NONE","None")))
NegEmoSupp <- NegEmoSupp %>% group_by(PID,entry,Target) %>% add_count(Target)

# Positive Emotional Support
PosEmoSupp <- select(data,c(PID,entry,Age,DID,NID,dorm,PosEmoSupp_1:PosEmoSupp_6))
PosEmoSupp <- gather(PosEmoSupp, key = "PosEmoSupp", value = "Target", PosEmoSupp_1:PosEmoSupp_6)
PosEmoSupp <- replace_with_na(PosEmoSupp, replace = list(Target = c("NONE","None")))
PosEmoSupp <- PosEmoSupp %>% group_by(PID,entry,Target) %>% add_count(Target)

# Responsive
Responsive <- select(data,c(PID,entry,Age,DID,NID,dorm,Responsive_1:Responsive_6))
Responsive <- gather(Responsive, key = "Responsive", value = "Target", Responsive_1:Responsive_6)
Responsive <- replace_with_na(Responsive, replace = list(Target = c("NONE","None")))
Responsive <- Responsive %>% group_by(PID,entry,Target) %>% add_count(Target)

# Empathic Support
EmpSupp <- select(data,c(PID,entry,Age,DID,NID,dorm,EmpSupp_1:EmpSupp_6))
EmpSupp <- gather(EmpSupp, key = "EmpSupp", value = "Target", EmpSupp_1:EmpSupp_6)
EmpSupp <- replace_with_na(EmpSupp, replace = list(Target = c("NONE","None")))
EmpSupp <- EmpSupp %>% group_by(PID,entry,Target) %>% add_count(Target)

# Positive Affect
PosAff <- select(data,c(PID,entry,Age,DID,NID,dorm,PosAffPres_1:PosAffPres_6))
PosAff <- gather(PosAff, key = "PosAff", value = "Target", PosAffPres_1:PosAffPres_6)
PosAff <- replace_with_na(PosAff, replace = list(Target = c("NONE","None")))
PosAff <- PosAff %>% group_by(PID,entry,Target) %>% add_count(Target)

# Negative Affect
NegAff <- select(data,c(PID,entry,Age,DID,NID,dorm,NegAffPres_1:NegAffPres_6))
NegAff <- gather(NegAff, key = "NegAff", value = "Target", NegAffPres_1:NegAffPres_6)
NegAff <- replace_with_na(NegAff, replace = list(Target = c("NONE","None")))
NegAff <- NegAff %>% group_by(PID,entry,Target) %>% add_count(Target)

# Gossip
Gossip <- select(data,c(PID,entry,Age,DID,NID,dorm,Gossip_1:Gossip_6))
Gossip <- gather(Gossip, key = "Gossip", value = "Target", Gossip_1:Gossip_6)
Gossip <- replace_with_na(Gossip, replace = list(Target = c("NONE","None")))
Gossip <- Gossip %>% group_by(PID,entry,Target) %>% add_count(Target)

# Persuasive
Persuasive <- select(data,c(PID,entry,Age,DID,NID,dorm,Persuasive_1:Persuasive_6))
Persuasive <- gather(Persuasive, key = "Persuasive", value = "Target", Persuasive_1:Persuasive_6)
Persuasive <- replace_with_na(Persuasive, replace = list(Target = c("NONE","None")))
Persuasive <- Persuasive %>% group_by(PID,entry,Target) %>% add_count(Target)

# Liked
Liked <- select(data,c(PID,entry,Age,DID,NID,dorm,Liked_1:Liked_6))
Liked <- gather(Liked, key = "Liked", value = "Target", Liked_1:Liked_6)
Liked <- replace_with_na(Liked, replace = list(Target = c("NONE","None")))
Liked <- Liked %>% group_by(PID,entry,Target) %>% add_count(Target)
```

## Summarize data

```{r, echo=FALSE}

# # Close friends
# hist(CloseFrds$n)
# mean(CloseFrds$n)
# median(CloseFrds$n)
# 
# # Spend time
# hist(SpendTime$n)
# mean(SpendTime$n)
# median(SpendTime$n)
# 
# # Social Advice
# hist(SocAdvice$n)
# mean(SocAdvice$n)
# median(SocAdvice$n)
# 
# # Negative Emotional Support
# hist(NegEmoSupp$n)
# mean(NegEmoSupp$n)
# median(NegEmoSupp$n)
# 
# # Positive Emotional Support
# hist(PosEmoSupp$n)
# mean(PosEmoSupp$n)
# median(PosEmoSupp$n)
# 
# # Responsive
# hist(Responsive$n)
# mean(Responsive$n)
# median(Responsive$n)
# 
# # Empathic Support
# hist(EmpSupp$n)
# mean(EmpSupp$n)
# median(EmpSupp$n)
# 
# # Positive Affect
# hist(PosAff$n)
# mean(PosAff$n)
# median(PosAff$n)
# 
# # Negative Affect
# hist(NegAff$n)
# mean(NegAff$n)
# median(NegAff$n)
# 
# # Gossip
# hist(Gossip$n)
# mean(Gossip$n)
# median(Gossip$n)
# 
# # Persuasive
# hist(Persuasive$n)
# mean(Persuasive$n)
# median(Persuasive$n)
# 
# # Liked
# hist(Liked$n)
# mean(Liked$n)
# median(Liked$n)
```

## Plot boxplot of number of targets by dorm

```{r, echo=FALSE, warning=FALSE}
library(gmodels)

# Close friends
CloseFrds %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

CloseFrds %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Close Friends") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 

# Spend Time
SpendTime %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

SpendTime %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Spend Time") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 

# Social Advice
SocAdvice %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

SocAdvice %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Social Advice") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 

# Negative Emotional Support
NegEmoSupp %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

NegEmoSupp %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Negative Emotional Support") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 

# Positive Emotional Support
PosEmoSupp %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

PosEmoSupp %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Positive Emotional Support") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 

# Responsive
Responsive %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

Responsive %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Responsive") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 

# Empathic Support
EmpSupp %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

EmpSupp %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Empathic Support") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 

# Positive Affect
PosAff %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

PosAff %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Positive Affect") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 

# Negative Affect
NegAff %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

NegAff %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Negative Affect") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 

# Gossip
Gossip %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

Gossip %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Gossip") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 

# Persuasive
Persuasive %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

Persuasive %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Persuasive") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 

# Liked
Liked %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

Liked %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Liked") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 
```

## Plot mean number of targets by dorm

```{r, echo=FALSE, warning=FALSE}
library(gmodels)

# Close friends
CloseFrds %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

CloseFrds %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Close Friends") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 

# Spend Time
SpendTime %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

SpendTime %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Spend Time") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 

# Social Advice
SocAdvice %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

SocAdvice %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Social Advice") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 

# Negative Emotional Support
NegEmoSupp %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

NegEmoSupp %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Negative Emotional Support") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 

# Positive Emotional Support
PosEmoSupp %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

PosEmoSupp %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Positive Emotional Support") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 

# Responsive
Responsive %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

Responsive %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Responsive") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 

# Empathic Support
EmpSupp %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

EmpSupp %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Empathic Support") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 

# Positive Affect
PosAff %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

PosAff %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Positive Affect") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 

# Negative Affect
NegAff %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

NegAff %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Negative Affect") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 

# Gossip
Gossip %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

Gossip %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Gossip") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 

# Persuasive
Persuasive %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

Persuasive %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Persuasive") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 

# Liked
Liked %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4])

Liked %>% group_by(dorm) %>% summarise(mean = ci(n)[1], lowCI = ci(n)[2], hiCI = ci(n)[3], sd = ci(n)[4]) %>%
  ggplot(aes(reorder(dorm,mean), mean, fill=dorm))+
  geom_bar(stat="identity", position = "dodge")+
  geom_errorbar(aes(ymin=lowCI, ymax=hiCI), position = "dodge") + theme_minimal() + ggtitle("Liked") +
  theme_minimal() + ylab("Number of Nominated Targets") + xlab("Dorm") + theme(legend.position="none") 
```